### ISSUE TITLE
hi, will this be updated? it doesn't seem to work on sublimetext 4.

### ISSUE THREAD

**Issue by LollipopFt** [rwols/SublimeLinter-contrib-clang-tidy#7]

**Comment by rwols** [comment]
What doesn’t work about it?

**Comment by LollipopFt** [comment]
@rwols sorry, i realised that i needed to make a compilation database. is there a way to run this without needing to set up all these extra steps like the compilation database since i am on windows and setting these up are a pain? i am ok with setting up a .clang-tidy though.

**Comment by mheinzler** [comment]
Without a compilation database clang-tidy will probably not report all errors or even show wrong ones as you're missing include paths and other compiler options. If you think you don't need it, you could try to provide an empty one and see if that is good enough. The plugin only checks that the file exists.

Otherwise you should use something like CMake for your project, which is able to generate the database as part of the build. If you are using Visual Studio, there should also be some options to create the file from your project.
